import { PokemonItem } from "../../../../interfaces/pokemon-item";

export const fishByGeneration: Record<number, PokemonItem[]> = {
  1: [
    // Water starter (Gen 1)
    { text: "pokemon.squirtle", pokemonId: 7, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },

    { text: "pokemon.psyduck", pokemonId: 54, fillStyle: "goldenrod", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.poliwag", pokemonId: 60, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.poliwhirl", pokemonId: 61, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.tentacool", pokemonId: 72, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.tentacruel", pokemonId: 73, fillStyle: "darkblue", sprite: null, shiny: false, power: 3, weight: 1 },
    { text: "pokemon.slowpoke", pokemonId: 79, fillStyle: "pink", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.slowbro", pokemonId: 80, fillStyle: "pink", sprite: null, shiny: false, power: 3, weight: 1 },
    { text: "pokemon.shellder", pokemonId: 90, fillStyle: "purple", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.krabby", pokemonId: 98, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.kingler", pokemonId: 99, fillStyle: "darkred", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.horsea", pokemonId: 116, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.seadra", pokemonId: 117, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.goldeen", pokemonId: 118, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.seaking", pokemonId: 119, fillStyle: "darkred", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.staryu", pokemonId: 120, fillStyle: "brown", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.magikarp", pokemonId: 129, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.gyarados", pokemonId: 130, fillStyle: "darkblue", sprite: null, shiny: false, power: 3, weight: 1 },
    { text: "pokemon.dratini", pokemonId: 147, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.dragonair", pokemonId: 148, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 }
  ],
  2: [
    // Water starter (Gen 2)
    { text: "pokemon.totodile", pokemonId: 158, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },

    { text: "pokemon.poliwag", pokemonId: 60, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.poliwhirl", pokemonId: 61, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.tentacool", pokemonId: 72, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.tentacruel", pokemonId: 73, fillStyle: "darkblue", sprite: null, shiny: false, power: 3, weight: 1 },
    { text: "pokemon.shellder", pokemonId: 90, fillStyle: "purple", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.krabby", pokemonId: 98, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.horsea", pokemonId: 116, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.seadra", pokemonId: 117, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.kingler", pokemonId: 99, fillStyle: "darkred", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.goldeen", pokemonId: 118, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.seaking", pokemonId: 119, fillStyle: "darkred", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.staryu", pokemonId: 120, fillStyle: "brown", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.magikarp", pokemonId: 129, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.gyarados", pokemonId: 130, fillStyle: "darkblue", sprite: null, shiny: false, power: 3, weight: 1 },
    { text: "pokemon.dratini", pokemonId: 147, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.dragonair", pokemonId: 148, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.chinchou", pokemonId: 170, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.lanturn", pokemonId: 171, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.qwilfish", pokemonId: 211, fillStyle: "gray", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.corsola", pokemonId: 222, fillStyle: "pink", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.remoraid", pokemonId: 223, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 }
  ],
  3: [
    // Water starter (Gen 3)
    { text: "pokemon.mudkip", pokemonId: 258, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },

    { text: "pokemon.tentacool", pokemonId: 72, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.tentacruel", pokemonId: 73, fillStyle: "darkblue", sprite: null, shiny: false, power: 3, weight: 1 },
    { text: "pokemon.horsea", pokemonId: 116, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.seadra", pokemonId: 117, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.goldeen", pokemonId: 118, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.seaking", pokemonId: 119, fillStyle: "darkred", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.magikarp", pokemonId: 129, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.corsola", pokemonId: 222, fillStyle: "pink", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.remoraid", pokemonId: 223, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.octillery", pokemonId: 224, fillStyle: "darkred", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.carvanha", pokemonId: 318, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.sharpedo", pokemonId: 319, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.wailmer", pokemonId: 320, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.wailord", pokemonId: 321, fillStyle: "darkblue", sprite: null, shiny: false, power: 3, weight: 1 },
    { text: "pokemon.barboach", pokemonId: 339, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.whiscash", pokemonId: 340, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.corphish", pokemonId: 341, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.crawdaunt", pokemonId: 342, fillStyle: "darkred", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.feebas", pokemonId: 349, fillStyle: "brown", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.relicanth", pokemonId: 369, fillStyle: "gray", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.luvdisc", pokemonId: 370, fillStyle: "pink", sprite: null, shiny: false, power: 1, weight: 1 }
  ],
  4: [
    // Water starter (Gen 4)
    { text: "pokemon.piplup", pokemonId: 393, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },

    { text: "pokemon.poliwag", pokemonId: 60, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.poliwhirl", pokemonId: 61, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.shellder", pokemonId: 90, fillStyle: "purple", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.horsea", pokemonId: 116, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.seadra", pokemonId: 117, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.goldeen", pokemonId: 118, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.seaking", pokemonId: 119, fillStyle: "darkred", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.magikarp", pokemonId: 129, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.gyarados", pokemonId: 130, fillStyle: "darkblue", sprite: null, shiny: false, power: 3, weight: 1 },
    { text: "pokemon.dratini", pokemonId: 147, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.dragonair", pokemonId: 148, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.chinchou", pokemonId: 170, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.lanturn", pokemonId: 171, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.qwilfish", pokemonId: 211, fillStyle: "gray", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.remoraid", pokemonId: 223, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.octillery", pokemonId: 224, fillStyle: "darkred", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.carvanha", pokemonId: 318, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.sharpedo", pokemonId: 319, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.wailmer", pokemonId: 320, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.wailord", pokemonId: 321, fillStyle: "darkblue", sprite: null, shiny: false, power: 3, weight: 1 },
    { text: "pokemon.barboach", pokemonId: 339, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.whiscash", pokemonId: 340, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.corphish", pokemonId: 341, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.crawdaunt", pokemonId: 342, fillStyle: "darkred", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.feebas", pokemonId: 349, fillStyle: "brown", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.clamperl", pokemonId: 366, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.relicanth", pokemonId: 369, fillStyle: "gray", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.luvdisc", pokemonId: 370, fillStyle: "pink", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.finneon", pokemonId: 456, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.lumineon", pokemonId: 457, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 }
  ],
  5: [
    // Water starter (Gen 5)
    { text: "pokemon.oshawott", pokemonId: 501, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },

    { text: "pokemon.poliwag", pokemonId: 60, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.poliwhirl", pokemonId: 61, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.poliwrath", pokemonId: 62, fillStyle: "darkblue", sprite: null, shiny: false, power: 3, weight: 1 },
    { text: "pokemon.shellder", pokemonId: 90, fillStyle: "purple", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.cloyster", pokemonId: 91, fillStyle: "purple", sprite: null, shiny: false, power: 3, weight: 1 },
    { text: "pokemon.krabby", pokemonId: 98, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.kingler", pokemonId: 99, fillStyle: "darkred", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.horsea", pokemonId: 116, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.seadra", pokemonId: 117, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.goldeen", pokemonId: 118, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.seaking", pokemonId: 119, fillStyle: "darkred", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.magikarp", pokemonId: 129, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.gyarados", pokemonId: 130, fillStyle: "darkblue", sprite: null, shiny: false, power: 3, weight: 1 },
    { text: "pokemon.dratini", pokemonId: 147, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.dragonair", pokemonId: 148, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.dragonite", pokemonId: 149, fillStyle: "brown", sprite: null, shiny: false, power: 4, weight: 1 },
    { text: "pokemon.chinchou", pokemonId: 170, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.lanturn", pokemonId: 171, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.marill", pokemonId: 183, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.azumarill", pokemonId: 184, fillStyle: "darkblue", sprite: null, shiny: false, power: 3, weight: 1 },
    { text: "pokemon.qwilfish", pokemonId: 211, fillStyle: "gray", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.corsola", pokemonId: 222, fillStyle: "pink", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.remoraid", pokemonId: 223, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.octillery", pokemonId: 224, fillStyle: "darkred", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.kingdra", pokemonId: 230, fillStyle: "darkblue", sprite: null, shiny: false, power: 3, weight: 1 },
    { text: "pokemon.carvanha", pokemonId: 318, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.sharpedo", pokemonId: 319, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.barboach", pokemonId: 339, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.whiscash", pokemonId: 340, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.feebas", pokemonId: 349, fillStyle: "brown", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.milotic", pokemonId: 350, fillStyle: "pink", sprite: null, shiny: false, power: 3, weight: 1 },
    { text: "pokemon.clamperl", pokemonId: 366, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.huntail", pokemonId: 367, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.gorebyss", pokemonId: 368, fillStyle: "pink", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.relicanth", pokemonId: 369, fillStyle: "gray", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.luvdisc", pokemonId: 370, fillStyle: "pink", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.finneon", pokemonId: 456, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.lumineon", pokemonId: 457, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.basculin", pokemonId: 550, fillStyle: "green", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.stunfisk", pokemonId: 618, fillStyle: "brown", sprite: null, shiny: false, power: 2, weight: 1 },
  ],
  6: [
    // Water starter (Gen 6)
    { text: "pokemon.froakie", pokemonId: 656, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },

    { text: "pokemon.poliwag", pokemonId: 60, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.poliwhirl", pokemonId: 61, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.poliwrath", pokemonId: 62, fillStyle: "darkblue", sprite: null, shiny: false, power: 3, weight: 1 },
    { text: "pokemon.shellder", pokemonId: 90, fillStyle: "purple", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.cloyster", pokemonId: 91, fillStyle: "purple", sprite: null, shiny: false, power: 3, weight: 1 },
    { text: "pokemon.goldeen", pokemonId: 118, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.seaking", pokemonId: 119, fillStyle: "darkred", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.staryu", pokemonId: 120, fillStyle: "brown", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.starmie", pokemonId: 121, fillStyle: "purple", sprite: null, shiny: false, power: 3, weight: 1 },
    { text: "pokemon.magikarp", pokemonId: 129, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.gyarados", pokemonId: 130, fillStyle: "darkblue", sprite: null, shiny: false, power: 3, weight: 1 },
    { text: "pokemon.dratini", pokemonId: 147, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.dragonair", pokemonId: 148, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.chinchou", pokemonId: 170, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.lanturn", pokemonId: 171, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.politoed", pokemonId: 186, fillStyle: "green", sprite: null, shiny: false, power: 3, weight: 1 },
    { text: "pokemon.qwilfish", pokemonId: 211, fillStyle: "gray", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.corsola", pokemonId: 222, fillStyle: "pink", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.remoraid", pokemonId: 223, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.octillery", pokemonId: 224, fillStyle: "darkred", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.carvanha", pokemonId: 318, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.sharpedo", pokemonId: 319, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.barboach", pokemonId: 339, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.whiscash", pokemonId: 340, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.corphish", pokemonId: 341, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.crawdaunt", pokemonId: 342, fillStyle: "darkred", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.clamperl", pokemonId: 366, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.huntail", pokemonId: 367, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.gorebyss", pokemonId: 368, fillStyle: "pink", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.luvdisc", pokemonId: 370, fillStyle: "pink", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.basculin", pokemonId: 550, fillStyle: "green", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.alomomola", pokemonId: 594, fillStyle: "pink", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.skrelp", pokemonId: 690, fillStyle: "brown", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.dragalge", pokemonId: 691, fillStyle: "brown", sprite: null, shiny: false, power: 3, weight: 1 },
    { text: "pokemon.clauncher", pokemonId: 692, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.clawitzer", pokemonId: 693, fillStyle: "darkblue", sprite: null, shiny: false, power: 3, weight: 1 }
  ],
  7: [
    // Water starter (Gen 7)
    { text: "pokemon.popplio", pokemonId: 728, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },

    { text: "pokemon.shellder", pokemonId: 90, fillStyle: "purple", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.goldeen", pokemonId: 118, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.seaking", pokemonId: 119, fillStyle: "darkred", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.staryu", pokemonId: 120, fillStyle: "brown", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.starmie", pokemonId: 121, fillStyle: "purple", sprite: null, shiny: false, power: 3, weight: 1 },
    { text: "pokemon.magikarp", pokemonId: 129, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.gyarados", pokemonId: 130, fillStyle: "darkblue", sprite: null, shiny: false, power: 3, weight: 1 },
    { text: "pokemon.dratini", pokemonId: 147, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.dragonair", pokemonId: 148, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.dragonite", pokemonId: 149, fillStyle: "brown", sprite: null, shiny: false, power: 4, weight: 1 },
    { text: "pokemon.chinchou", pokemonId: 170, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.lanturn", pokemonId: 171, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.corsola", pokemonId: 222, fillStyle: "pink", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.remoraid", pokemonId: 223, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.octillery", pokemonId: 224, fillStyle: "darkred", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.carvanha", pokemonId: 318, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.sharpedo", pokemonId: 319, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.wailmer", pokemonId: 320, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.wailord", pokemonId: 321, fillStyle: "darkblue", sprite: null, shiny: false, power: 3, weight: 1 },
    { text: "pokemon.barboach", pokemonId: 339, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.whiscash", pokemonId: 340, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.corphish", pokemonId: 341, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.crawdaunt", pokemonId: 342, fillStyle: "darkred", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.feebas", pokemonId: 349, fillStyle: "brown", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.clamperl", pokemonId: 366, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.huntail", pokemonId: 367, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.gorebyss", pokemonId: 368, fillStyle: "pink", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.relicanth", pokemonId: 369, fillStyle: "gray", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.luvdisc", pokemonId: 370, fillStyle: "pink", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.finneon", pokemonId: 456, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.lumineon", pokemonId: 457, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.basculin", pokemonId: 550, fillStyle: "green", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.alomomola", pokemonId: 594, fillStyle: "pink", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.skrelp", pokemonId: 690, fillStyle: "brown", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.dragalge", pokemonId: 691, fillStyle: "brown", sprite: null, shiny: false, power: 3, weight: 1 },
    { text: "pokemon.clauncher", pokemonId: 692, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.clawitzer", pokemonId: 693, fillStyle: "darkblue", sprite: null, shiny: false, power: 3, weight: 1 },
    { text: "pokemon.wishiwashi", pokemonId: 746, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.pyukumuku", pokemonId: 771, fillStyle: "black", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.dhelmise", pokemonId: 781, fillStyle: "green", sprite: null, shiny: false, power: 3, weight: 1 }
  ],
  8: [
    // Water starter (Gen 8)
    { text: "pokemon.sobble", pokemonId: 816, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },

    { text: "pokemon.chewtle", pokemonId: 833, fillStyle: "green", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.drednaw", pokemonId: 834, fillStyle: "brown", sprite: null, shiny: false, power: 3, weight: 1 },
    { text: "pokemon.arrokuda", pokemonId: 846, fillStyle: "brown", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.barraskewda", pokemonId: 847, fillStyle: "brown", sprite: null, shiny: false, power: 3, weight: 1 }
  ],

  // Gen 9 (Paldea) - all Water-type Pokémon introduced in this generation,
  // excluding Legendary/Mythical Pokémon and Paradox Pokémon
  9: [
    { text: "Quaxly", pokemonId: 912, fillStyle: "darkblue", sprite: { front_default: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/912.png', front_shiny: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/shiny/912.png' }, shiny: false, power: 1, weight: 1 },
    { text: "Quaxwell", pokemonId: 913, fillStyle: "darkblue", sprite: { front_default: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/913.png', front_shiny: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/shiny/913.png' }, shiny: false, power: 2, weight: 1 },
    { text: "Quaquaval", pokemonId: 914, fillStyle: "darkblue", sprite: { front_default: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/914.png', front_shiny: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/shiny/914.png' }, shiny: false, power: 3, weight: 1 },
    { text: "Wiglett", pokemonId: 960, fillStyle: "darkblue", sprite: { front_default: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/960.png', front_shiny: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/shiny/960.png' }, shiny: false, power: 1, weight: 1 },
    { text: "Wugtrio", pokemonId: 961, fillStyle: "darkblue", sprite: { front_default: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/961.png', front_shiny: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/shiny/961.png' }, shiny: false, power: 3, weight: 1 },
    { text: "Finizen", pokemonId: 963, fillStyle: "darkblue", sprite: { front_default: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/963.png', front_shiny: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/shiny/963.png' }, shiny: false, power: 1, weight: 1 },
    { text: "Palafin", pokemonId: 964, fillStyle: "darkblue", sprite: { front_default: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/964.png', front_shiny: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/shiny/964.png' }, shiny: false, power: 3, weight: 1 },
    { text: "Veluza", pokemonId: 976, fillStyle: "darkblue", sprite: { front_default: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/976.png', front_shiny: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/shiny/976.png' }, shiny: false, power: 2, weight: 1 },
    { text: "Dondozo", pokemonId: 977, fillStyle: "darkblue", sprite: { front_default: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/977.png', front_shiny: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/shiny/977.png' }, shiny: false, power: 3, weight: 1 },
    { text: "Tatsugiri", pokemonId: 978, fillStyle: "darkblue", sprite: { front_default: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/978.png', front_shiny: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/shiny/978.png' }, shiny: false, power: 2, weight: 1 }
  ]
};
